Add files via upload
AlexanderBurkhardt-IER/Power-system-analysis pull request #7
Opened 2023-06-20 17:47 UTC by choppa98

2023-06-21 07:37 UTC, LippkauFelix requested changes

2023-06-21 07:37 UTC, LippkauFelix commented on main.py
> +agg_region2 = aggregate_regions.loc[2,:].values.flatten().tolist()[0]
same here

2023-06-21 07:52 UTC, LippkauFelix requested changes

2023-06-21 07:52 UTC, LippkauFelix commented on main.py
> +out = out[out.Region != "DEU"]
at this stage of code out should not include any aggregated region? Please check this again.

2023-06-21 12:44 UTC, choppa98 commented on main.py
> +out = out[out.Region != "DEU"]
it does have deu, eu and panEU

2023-06-21 12:44 UTC, choppa98 commented on main.py
> +agg_region2 = aggregate_regions.loc[2,:].values.flatten().tolist()[0]
same [0] will give agg_region in that row and [1] all the regions to aggregate

2023-06-21 14:40 UTC, LippkauFelix commented on main.py
> +agg_region1 = aggregate_regions.loc[1,:].values.flatten().tolist()[0]
sorry, you are right! Unfortunately we are at the starting point for the error that Alex mentioned

2023-06-22 11:09 UTC, choppa98 commented on main.py
> +agg_region1 = aggregate_regions.loc[1,:].values.flatten().tolist()[0]
ok I totally forgot that we didn't have 'scenario' until the end in main.py, so groupby scenario returns an empty dataframe. I will push the changes.

2023-06-22 12:23 UTC, LippkauFelix approved these changes

2023-06-22 12:23 UTC, AlexanderBurkhardt-IER approved these changes

2023-06-22 12:29 UTC, merged

2023-06-22 13:02 UTC, AlexanderBurkhardt-IER reviewed
Works